version: "3.5"

services:
  service-sql:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: database-sql
    restart: always
    ports:
    - 1434:1433
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Mellizo55
    networks:
    -  aforo255-test
  service-mysql:
    image: mysql:8.0.26
    container_name: database-mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=Mellizo55
    ports:
    - 3307:3306
    - 33061:33060
    networks:
    - aforo255-test

networks:
   aforo255-test:
    name: micro
